### Criar um novo endereço***ok
POST http://localhost:3000/endereco
Content-Type: application/json

{
  "enderecoclient": "Rua Exemplo, 123",
  "cepclient": "12345678",
  "lat": -23.5505,
  "lon": -46.6333,
  "status": 1,
  "sedeclient": 1
}



### Listar todos os endereços***ok
GET http://localhost:3000/endereco



### Buscar endereço por ID***ok
GET http://localhost:3000/endereco/2


### Atualizar endereço***ok
PUT http://localhost:3000/endereco/2
Content-Type: application/json

{
  "enderecoendereco": "Rua Atualizada, 456",
  "enderecocep": "87654321",
  "enderecolat": -23.5505,
  "enderecolon": -46.6333,
  "enderecostatus": 1,
  "idsede": 1
}

### Deletar endereço***ok
DELETE http://localhost:3000/endereco/2


### Listar sedes***ok
GET http://localhost:3000/sede


### Listar sedes por id***ok
GET http://localhost:3000/sede/1
ok


### Atualizar sede
PUT http://localhost:3000/sede/3
Content-Type: application/json

{
  "nomesede": "Sede Atualizada",
  "status": 1
}

### deletar sede***ok
delete http://localhost:3000/sede/2



