name: Deploy para Servidor SSH

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
        - name: Fazer checkout do código
          uses: actions/checkout@v4
            
        - name: Configurar Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '22'
                
        - name: Instalar e buildar frontend
          run: |
            cd front
            npm i
            npm run build
                
        - name: Instalar e buildar backend
          run: |
            cd back
            npm i
            npm run build
            npx prisma generate
                
        - name: Copiar frontend para servidor
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            source: "front/dist/"
            target: "/dados/laudinho/frontend/"
            strip_components: 2
            
        - name: Copiar backend para servidor
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            source: "back/dist/,back/package.json,back/package-lock.json,back/prisma/"
            target: "/dados/laudinho/backend/"
            strip_components: 1
            
        - name: Instalar dependências e reiniciar aplicação
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            script: |
              pkill -f "node.*backend" || true
              cd /dados/laudinho/backend
              npm ci --only=production --ignore-scripts
              npx prisma generate
              nohup node index.js > app.log 2>&1 &