name: Deploy para Servidor SSH

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
        - name: Fazer checkout do código
          uses: actions/checkout@v4
            
        - name: Configurar Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '22'
                
        - name: Instalar e buildar frontend
          run: |
            cd front
            npm i
            npm run build
                
        - name: Instalar e buildar backend
          run: |
            cd back
            npm i
            npm run build
            # Generate Prisma client for production
            npx prisma generate
                
        - name: Copiar frontend para servidor
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            source: "front/dist/"
            target: "/dados/laudinho/frontend/"
            strip_components: 2
            
        - name: Copiar backend para servidor
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            source: "back/dist/,back/package.json,back/package-lock.json,back/prisma/"
            target: "/dados/laudinho/backend/"
            strip_components: 1
            
        - name: Instalar dependências e reiniciar aplicação
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            timeout: 300s
            command_timeout: 300s
            script: |
              # Stop existing process
              pkill -f "node.*backend" || true
              sleep 2
              
              # Navigate to backend directory
              cd /dados/laudinho/backend
              
              # Install dependencies with longer timeout
              echo "Installing dependencies..."
              npm ci --only=production --ignore-scripts --timeout=300000
              
              # Generate Prisma client
              echo "Generating Prisma client..."
              npx prisma generate
              
              # Start application in background
              echo "Starting application..."
              nohup node index.js > app.log 2>&1 &
              
              # Verify it started
              sleep 3
              if pgrep -f "node.*index.js" > /dev/null; then
                echo "Application started successfully"
              else
                echo "Failed to start application"
                exit 1
              fi